### ISSUE TITLE
unicode in pkginfo plist produces error

### ISSUE THREAD

**Issue by dayglojesus** [jnraine/munkiserver#108]
Pkginfo plist files that contain unicode characters cannot be uploaded via the package-add form. 

Such files produce the error:

Completed 500 Internal Server Error in 44ms

Encoding::CompatibilityError (incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)):
  app/models/package.rb:820:in `process_pkginfo_file'
  app/models/package.rb:776:in `process_package_file'
  app/models/package.rb:682:in `create'
  app/controllers/packages_controller.rb:51:in `create'

**Comment by rickychilcott** [comment]
This has been fixed for a while, since 7938c84035f1739cecd2378da42aa398410ec679
