### ISSUE TITLE
need to be able to delete multiple packages simultaneously

### ISSUE THREAD

**Issue by dayglojesus** [jnraine/munkiserver#117]
The larger a repo gets, the more difficult it is to maintain. Being able to prune old packages out your repo is becoming critical to ensuring a well organized unit.

Having to delete a single package at a time, is more than inconvenient now -- it's time consuming and frustrating.

**Comment by rickychilcott** [comment]
Fixed in https://github.com/munkiserver/munkiserver/pull/13
