### ISSUE TITLE
Version numbers sorted incorrectly

### ISSUE THREAD

**Issue by treydock** [jnraine/munkiserver#131]
I noticed today that version numbers of varying length seem to be evaluated as strings rather than integers when sorted in the Package bundle view.

An Example, Firefox showed this

10.0.1 10.0.2 8.0.1 

The same behavior exists in the package index view...

8.0.1
10.0.2
10.0.1

Patch incoming shortly...fixing the index page is slightly more complicated than the unit page.

**Comment by rickychilcott** [comment]
Same as #171. Resolved
