### ISSUE TITLE
Issues downloading catalogs

### ISSUE THREAD

**Issue by vw0rp** [jnraine/munkiserver#154]
Okay, so I've had the latest master (as of this timestamp) running for a wee while. I've been adding a great number of packages lately, but I think a package has broken the catalogs controller. If one browses to `http://<munkiserver>/catalogs/1-Production.plist` for instance, they get a HTTP 500 error. The `<proj>/log/production.log` file spits out the following logging:

    Started GET "/catalogs/1-Production.plist" for 1.1.1.1 at 2012-09-03 15:01:14 +1200
    Processing by CatalogsController#show as PLIST
      Parameters: {"unit_environment"=>"1-Production"}
        CACHE: Geneterating catalog for {:type=>:catalog, :unit=>"1", :environment_id=>2}
    Completed 500 Internal Server Error in 1114ms
    
    NoMethodError (undefined method `first' for nil:NilClass):
      app/models/behaviours/is_an_item.rb:28:in `package'
      app/models/package.rb:402:in `update_for'

I tried running the [destroy_stale_item_records](https://github.com/jnraine/munkiserver/commit/496122e03314515cee6d105aaeda4e5b17d9c6c1) chore but that too seemed to have a problem:

    $ rake --trace chore:destroy_stale_item_records RAILS_ENV=production
    ** Invoke chore:destroy_stale_item_records (first_time)
    ** Invoke environment (first_time)
    ** Execute environment
    Cannot find or read /Users/macadmin1/munkiserver/config/newrelic.yml
    ** Execute chore:destroy_stale_item_records
    rake aborted!
    undefined method `destroy_stale_records' for #<Class:0x007f8eb9d31748>
    /Users/macadmin1/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.2/lib/active_record/dynamic_matchers.rb:50:in `method_missing'
    -- snip --

Am I doing something wrong, or have I stumbled on a bug somewhere?

**Comment by rickychilcott** [comment]
These two issues have been fixed in future releases
