### ISSUE TITLE
Version numbers use lexical sorting instead of numerical sorting

### ISSUE THREAD

**Issue by mkuron** [jnraine/munkiserver#171]
In the packages list and in the version selection at the top of the edit package page, packages are sorted by version number. However, the sorting appears to use lexical sorting instead of numerical sorting. This results in a sort order like
1.6.2
1.6.16
1.6.13
1.4.17
1.4.12

Even worse, this sorting causes the update check email notification to tell me that version 3.0.10 is available when I have both 3.0.9 and 3.0.10 in my repository as it only compares the current version number (3.0.10) against the one it considers to be the latest version (3.0.9) and does so lexically.

**Comment by rickychilcott** [comment]
This has been fixed in https://github.com/munkiserver/munkiserver/pull/8 and https://github.com/munkiserver/munkiserver/pull/4
